# Generated by Django 4.1.1 on 2022-10-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='permission',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contributors',
            name='role',
            field=models.CharField(blank=True, choices=[('Responsable', 'Responsable'), ('Dev', 'Dev')], default='Dev', max_length=128),
        ),
    ]
